name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-graph:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Generate contribution graph
        run: |
          mkdir -p output
          curl -o output/pacman-contribution-graph.svg "https://ghchart.rshah.org/2ecc71/Nikk-123"
          curl -o output/pacman-contribution-graph-dark.svg "https://ghchart.rshah.org/2ecc71/Nikk-123?dark=true"
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update contribution graph" && git push) 